// // src/store/houseData.js
// const houseData = [
//   {
//     id: 1,
//     title: 'Beautiful House 1',
//     description: 'This is a beautiful house with a large garden.',
//     price: 250000,
//     type: 'Single storey',
//     BHK: 3,
//     Ac: 'yes',
//     imageUrl: 'https://www.rocketmortgage.com/resources-cmsassets/RocketMortgage.com/Article_Images/Large_Images/TypesOfHomes/types-of-homes-hero.jpg',
//   },
//   {
//     id: 2,
//     title: 'Cozy House 2',
//     description: 'A cozy house with a fireplace and stunning view.',
//     price: 180000,
//     type: 'Double Storey',
//     BHK: 2,
//     Ac: 'No',
//     imageUrl: 'https://housing.com/news/wp-content/uploads/2022/11/shutterstock_1715891752-1200x700-compressed.jpg',
//   },
//   {
//     id: 3,
//     title: 'Cozy House 3',
//     description: 'A cozy house with a fireplace and stunning view.',
//     price: 180000,
//     type: 'Double Storey',
//     BHK: 3,
//     AC: 'yes',
//     imageUrl: 'https://assets-news.housing.com/news/wp-content/uploads/2022/04/07013406/ELEVATED-HOUSE-DESIGN-FEATURE-compressed.jpg',
//   },
//   {
//     id: 4,
//     title: 'Cozy House 4',
//     description: 'A cozy house with a fireplace and stunning view.',
//     price: 180000,
//     type: 'single storey',
//     BHK: 3,
//     AC: 'No',
//     imageUrl: 'https://thumbs.dreamstime.com/z/beautiful-exterior-home-pictures-new-home-design-images-modern-best-house-design-images-best-house-images-images-latest-172194515.jpg',
//   },
//   {
//     id: 5,
//     title: 'Cozy House 5',
//     description: 'A cozy house with a fireplace and stunning view.',
//     price: 180000,
//     type: 'Duble Storey',
//     BHK: 2,
//     AC: 'yes',
//     imageUrl: 'https://images.coolhouseplans.com/plans/80523/80523-b440.jpg',
//   },
//   {
//     id: 6,
//     title: 'Cozy House 6',
//     description: 'A cozy house with a fireplace and stunning view.',
//     price: 180000,
//     type: 'single Storey',
//     BHK: 3,
//     Ac: 'No',
//     imageUrl: 'https://www.nobroker.in/blog/wp-content/uploads/2022/07/Small-House-Designs.jpg',
//   },
//   {
//     id: 7,
//     title: 'Cozy House 7',
//     description: 'A cozy house with a fireplace and stunning view.',
//     price: 180000,
//     type: 'Double storey',
//     BHK: 3,
//     AC: 'yes',
//     imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLZoRD0K8p5aZ0PH_03Qz0nxACra-IW2syxg&usqp=CAU',
//   },
//   {
//     id: 8,
//     title: 'Cozy House 8',
//     description: 'A cozy house with a fireplace and stunning view.',
//     price: 180000,
//     type: 'Single Storey',
//     BHK: 3,
//     AC: 'yes',
//     imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bHV4dXJ5JTIwaG91c2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80',
//   },
//   // Add more house objects here...
// ];

// export default houseData;
